[pytest]
testpaths =
    02-技术研发/01-数据采集/tests
    02-技术研发/02-信号处理/tests
    02-技术研发/05-通信协议/tests
    02-技术研发/07-数据治理/tests
    02-技术研发/tests
norecursedirs =
    02-技术研发/03-TouchDesigner/mcp_td_v147
    02-技术研发/04-Unity视觉/SRP-Weather-Visual/Library
    02-技术研发/04-Unity视觉/SRP-Weather-Visual/Temp
    tmp
addopts = -p no:cacheprovider
